

version: '3.8'

networks:
  my_network:
    driver: bridge

services:

  nodeapp1:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - nodeapp1-data:/app/data
    env_file:
      - ./.env
    networks:
      - my_network
  
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: xclonedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d  # Mount the init-scripts directory
    networks:
      - my_network

  redis:
    image: "redis:latest"
    command: ["redis-server", "--maxmemory", "1g"]
    ports:
      - "6379:6379"
    networks:
      - my_network

volumes:
  nodeapp1-data:
  postgres-data:
